# Generated by Django 2.1.15 on 2020-12-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Location')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_target', to='map.Location')),
            ],
        ),
    ]
